### PR TITLE
[FIX] now showing images from both ir.attachments and binary image of the product itself

### PR DESCRIPTION
**Pull request by oscarolar**
BUILD https://github.com/Vauxoo/yoytec/pull/398

### CODE REVIEW

**Comment by oscarolar** [comment]
**_Backend With no image but with attachments:**_
noatt
**_Image if there is not image on the `image` field of the product but there are on the  `ir.attachment` model:**_
image
**_Attachments shown in website:**_
att

**Comment by oscarolar** [comment]
@nhomar @moylop260 can you review this PR in order to merge it or do further changes, you can test it with the runbot generated here https://github.com/Vauxoo/yoytec/pull/398

**Comment by nhomar** [comment]
@oscarolar the demo data is not being shown with public user:

This is what I see.

ds

**Comment by nhomar** [comment]
@oscarolar it fails also logged in.

sds

**Comment by oscarolar** [comment]
@nhomar  It must not fail now, its a Runbot error, @moylop260 is fixing it, it has a temporary fix. if you check it now it must work.

**Comment by jholze** [comment]
:+1:

**Pull request merged**
